[package]
name = "RunIfNot"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
sysinfo = "0.30"

# サイズを小さくするための設定
[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"